from flask import Flask, render_template, url_for, request, redirect, session
import csv, random, time

app = Flask(__name__)
app.secret_key = "averylongsecretkey"


movie_list = [] #list of all movies
total_movie_number = 0 #total number of movies
generated_movie_name = ""


with open("bollydumb_movielist.csv","r") as file:
	movie_list = list(csv.reader(file))
	total_movie_number = len(movie_list) - 1



def generateMovieName():

	def generateRandomNumber():
		r = random.randint(1,total_movie_number)
		return r

	n = generateRandomNumber()

	generated_movie_name = movie_list[n][1]
	
	return generated_movie_name


session_list = []


@app.route('/', methods=['POST', 'GET'])
def index():
	global session_list
	session['usr_gen_list'] = session_list #list generated by user to be stored in flask session variable
	
	generated_movie_name2 = generateMovieName()

	if len(session_list) == total_movie_number:
		session['usr_gen_list'] = []
		session_list = []
		session_list.append(generated_movie_name2)

	while generated_movie_name2 in session['usr_gen_list']:
		generated_movie_name2 = generateMovieName()

	nlist = session['usr_gen_list']
	nlist.append(generated_movie_name2)
	session['usr_gen_list'] = nlist
	# print(session['usr_gen_list']) #for testing purpose
	# print(session_list)			 #for testing purpose

	return render_template('index.html', generated_movie_name=generated_movie_name2, session_list=session['usr_gen_list'])


@app.route('/about/')
def about():
	return render_template('about.html')


if __name__ == "__main__":
	app.run(debug=False)